repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: build
        name: build
        description: build the project
        entry: cargo build
        pass_filenames: false
        language: rust
      - id: format
        name: format
        description: run cargo fmt
        entry: cargo fmt
        pass_filenames: false
        language: rust
      - id: fix-style
        name: fix-style
        description: fix issues using cargo clippy
        entry: cargo clippy --fix --allow-staged
        pass_filenames: false
        language: rust
      - id: show-warnings
        name: show-warnings
        description: show clippy show-warnings
        entry: cargo clippy
        pass_filenames: false
        language: rust
